version: '3.8'

services:
  openhab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENHAB_VERSION: ${OPENHAB_VERSION:-4.1.0.M3}
        IS_MILESTONE: ${IS_MILESTONE:-true}
    image: ghcr.io/jannegpriv/openhab-container:${OPENHAB_VERSION:-4.1.0.M3}
    container_name: openhab
    working_dir: /openhab
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - openhab_conf:/openhab/conf
      - openhab_userdata:/openhab/userdata
      - openhab_addons:/openhab/addons
    environment:
      - USER_ID=9001
      - GROUP_ID=9001
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Stockholm
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8101:8101"
      - "5007:5007"
    restart: unless-stopped

volumes:
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local
  openhab_addons:
    driver: local
