name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    # Handle both regular releases and milestone releases
    tags: 
      - 'v*.*.*'           # Regular releases like v4.1.1
      - 'v*.*.*.M*'        # Milestone releases like v4.1.1.M1
      - 'v*.*.*.m*'        # Lowercase milestone like v4.1.1.m1
      - 'v*-milestone.*'   # Alternative milestone format
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=match,pattern=v(.*),group=1
            type=match,pattern=v([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}),group=1
            type=match,pattern=v([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.M[0-9]+),group=1
            type=match,pattern=v([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.m[0-9]+),group=1
            type=match,pattern=v([0-9]{1,3})-milestone\.([0-9]+),group=1

      - name: Extract version and milestone status
        id: version
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's|^refs/tags/v||')
            if [[ "$VERSION" =~ [Mm][0-9]+ ]]; then
              echo "is_milestone=true" >> $GITHUB_OUTPUT
            else
              echo "is_milestone=false" >> $GITHUB_OUTPUT
            fi
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "is_milestone=false" >> $GITHUB_OUTPUT
            echo "version=4.1.1" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            OPENHAB_VERSION=${{ steps.version.outputs.version }}
            IS_MILESTONE=${{ steps.version.outputs.is_milestone }}
